### ISSUE TITLE
Issues on Backstage 1.23.4

### ISSUE THREAD

**Issue by danielgonzalez3** [deepan10/backstage-plugin-blackduck#5]
After bumping to a later version of backstage:
https://backstage.github.io/upgrade-helper/?from=1.14.0&to=1.23.4

I ran into the following issue:
![image](https://github.com/deepan10/backstage-plugin-blackduck/assets/44592329/a949a0cf-217a-48ad-a543-26ca877f7c90)

Anyway we can bump packages to match react on latest backstage?

**Comment by deepan10** [comment]
Hello @danielgonzalez3 

Yeah I will release a new version to match the latest Backstage.

**Comment by danielgonzalez3** [comment]
any luck on this? I believe the backstage cli can auto resolve/update core packages

**Comment by deepan10** [comment]
Hello @danielgonzalez3 
Yes, The next version is already available in npmjs.com. That you can consume for now I will update the documentation part and make a  proper release.

Frontend - https://www.npmjs.com/package/backstage-plugin-blackduck/v/1.2.1-next
Backend - https://www.npmjs.com/package/backstage-plugin-blackduck-backend/v/0.1.0-next

**Comment by deepan10** [comment]
Hello @danielgonzalez3,

A new version is released to support the Backstage version 1.23.x.
